//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persets.Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentShareBetweenUsers
    {
        public string GUID { get; set; }
        public string ContentGUIDToBeShared { get; set; }
        public string UserGUIDToShare { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual Users Users { get; set; }
    }
}
