//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persets.Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Content()
        {
            this.ContentShareBetweenUsers = new HashSet<ContentShareBetweenUsers>();
        }
    
        public string GUID { get; set; }
        public string UserGUID { get; set; }
        public string CategoryGUID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string PhysicalFile { get; set; }
        public long ViewsNumber { get; set; }
        public long DownloadsNumber { get; set; }
        public bool PrivacyPublic { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentShareBetweenUsers> ContentShareBetweenUsers { get; set; }
    }
}
